#!/bin/sh

mkdir -f /usr/share/cb/integrations/cyphort/db
chkconfig --add cb-cyphort-connector
chkconfig --level 345 cb-cyphort-connector on

# not auto-starting because conf needs to be updated
#/etc/init.d/cb-cyphort-connector start
